### PR TITLE
improved UI to show selected value

### PR DESCRIPTION
**Pull request by kasparsj**

### CODE REVIEW

**Comment by roymacdonald** [comment]
Hey! thanks. 
the feature showing the selected option is nice. It was one of my TO DOs.
I just noticed that with the previous PR you did, when you make a multiple selection you can no longer deselect these. 
Please fix that and add it to this PR.
cheers.

**Comment by kasparsj** [comment]
Hey. I fixed multi selection by making it depend on the ofParameter, if ofParameter<vector> is passed to the constructor, then it will work on multi-select mode.

**Comment by roymacdonald** [comment]
Hey Thanks.
I think that we are driving into the wrong direction. I mean it is not your fault but your commits made me think about the whole design of this addon.
My idea is to have this added to the main ofxGui repo, but as such it should follow the logic behind ofxGui. In that sense, it should receive an ofParameter or an ofParameterGroup and use the event listener to publish the changes made to the dropdown. Having it this way would allow for a more logical integration with the whole ofxGui design. Also, I think there is no need to reimplement things that are already there, so for the text I'd rather have an ofxLabel to handle it. The multiselection problem was in the setValue function, for which I already made a fix https://github.com/roymacdonald/ofxDropdown/commit/3ba19854449e6df834c2226af2a2207449cb348f
I have some more done already but not commited yet, I will finish it and see how it merges with your code.
Thanks again.

**Comment by kasparsj** [comment]
Ah, I thought maybe you meant that, but then I saw that multi selection was broken in the way that the ofParameter would hold only the last value. So had to make quite many changes to be able to store all selected values in case of a multi select drop-down.

**Comment by roymacdonald** [comment]
Sure, I get what you did. But I was thinking that using an ofParameterGroup would be better. I have a more or less clear picture about how to deal with the multi parameter. I'll push soon. I'll let you know.
thanks again.

**Pull request closed without merging**
