### PR TITLE
win32 register event

### PR DESCRIPTION
**Pull request by pierrextardif**
tested against of_0.11.2 with windows 10, register event needed previous implementeation.

### CODE REVIEW

**Comment by roymacdonald** [comment]
Thanks @pierrextardif but why it does not work? Today I will have access to a windows machine and I can debug it.

**Comment by pierrextardif** [comment]
ofxDropDown is missing the `mouseEntered` and `mouseExited` callback listeners, could also be patched with adding them:
```
    virtual void mouseEntered(ofMouseEventArgs&) override{
    }
    virtual void mouseExited(ofMouseEventArgs&) override{
    }
```
 inside `ofxDropDown.h` and `ofxDropdownOptions.hpp`

**Comment by pierrextardif** [comment]
let me know what youy think of it, i think this works better.

**Comment by roymacdonald** [comment]
Hey @pierrextardif thanks for this PR. I implemented it correctly (without an ifdef) and tested on win and mac and works as expected. I just pushed it to this repo.
Let me know if it works for you.

**Comment by pierrextardif** [comment]
I'm back on ubuntu for the night,m will report back in the morngin once tested, seems better to remove all #ifdef all together for sure.

**Comment by roymacdonald** [comment]
cool.thanks

**Comment by pierrextardif** [comment]
works fine!

**Comment by roymacdonald** [comment]
awesome. thanks!

**Pull request closed without merging**
