### PR TITLE
Onmouseover

### PR DESCRIPTION
**Pull request by Jonathhhan**
This pr shows the option onmouseover and hides them onmouseout. The click function for that is disabled.
Would be nice to have it as an option.

### CODE REVIEW

**Comment by roymacdonald** [comment]
thanks. let me look at this. but I'd rather have it as an option than overiding the default behaviour. I've been using this on touch devices and there the mouse over does not work...

**Comment by Jonathhhan** [comment]
Yes, I think that makes sense. I just was not able to implement it as an option. It would also make sense, if mouse click is the default.

**Comment by Jonathhhan** [comment]
@roymacdonald it also seems to work with touchpad with the change (but would still be nice, to be able to change the option).

**Comment by roymacdonald** [comment]
hey @Jonathhhan . I just pushed an update with the mouse over feature. Please check it and let me know what you think.
I decided to make it static, as it does not seem to be an option that someone would want to enable/disable per instance.

```
// where T is the templated type of your dropdown, like string, int, etc.

 ofxDropdown_<T>::enableShowWhenOver();
 ofxDropdown_<T>::disableShowWhenOver();
 ofxDropdown_<T>::isShowWhenOverEnabled();

```

you can also use the typedefs
```
ofxDropdown::enableShowWhenOver();
ofxIntDropdown::enableShowWhenOver();
ofxDirDropdown::enableShowWhenOver();


```

**Comment by Jonathhhan** [comment]
@roymacdonald very nice, thank you.
I am away from the computer for a good week, but will test it soon afterwards...

**Comment by Jonathhhan** [comment]
@roymacdonald I tested it and there is somehow a one pixel gap between dropdown and options.
I solved it like that:
```
		if(!b.inside(args.x-1, args.y)){
			hideDropdown();
			return true;
		}
```
And I think its nicer, if the click behavior is disabled with onmouseover (like here: https://mtest.handmadeproductions.de/), but maybe thats a matter of taste.

**Pull request closed without merging**
